/// Flutter icons BoxGameIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BoxGameIcons
///      fonts:
///       - asset: fonts/BoxGameIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BoxGameIcons {
  BoxGameIcons._();

  static const _kFontFam = 'BoxGameIcons';
  static const _kFontPkg = null;

  static const IconData suitcase = IconData(0xf0f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_alt = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down_alt = IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
